package timetablemanagement.View;



import timetablemanagement.Database.DBconnecter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL'
 */
public class AddLecturer extends javax.swing.JFrame {

    Connection con=null;
    /**
     * Creates new form AddLecturer
     */
    public AddLecturer() {
        initComponents();
        txtRank.setEditable(false);
         con=DBconnecter.connection();
    }

     private void Clear(){
        txtEmpID.setText("");
        txtLecName.setText("");
        dropFaculty.setSelectedIndex(0);
        dropDepart.setSelectedIndex(0);
        dropCenter.setSelectedIndex(0);
        dropBuilding.setSelectedIndex(0);
        dropLevel.setSelectedIndex(0);
        txtRank.setText("");
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtLecName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dropCenter = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtEmpID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dropBuilding = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        dropFaculty = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        dropLevel = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        dropDepart = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtRank = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(970, 500));
        getContentPane().setLayout(null);

        jPanel1.setLayout(new java.awt.GridLayout(4, 4, 5, 10));

        jLabel2.setText("Lecture Name");
        jPanel1.add(jLabel2);

        txtLecName.setName("txtName"); // NOI18N
        txtLecName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLecNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtLecName);

        jLabel3.setText("Center");
        jPanel1.add(jLabel3);

        dropCenter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Malabe", "Metro", "Matara", "Kandy", "Kurunagala", "Jaffna" }));
        jPanel1.add(dropCenter);

        jLabel4.setText("Enployee ID");
        jPanel1.add(jLabel4);

        txtEmpID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmpIDKeyTyped(evt);
            }
        });
        jPanel1.add(txtEmpID);

        jLabel5.setText("Building");
        jPanel1.add(jLabel5);

        dropBuilding.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "New building", "A-Block", "B-Block", "C-Block", "D-Block" }));
        jPanel1.add(dropBuilding);

        jLabel6.setText("Faculty");
        jPanel1.add(jLabel6);

        dropFaculty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computing", "Engineering", "Business", "Humanities", "Sciences" }));
        dropFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropFacultyActionPerformed(evt);
            }
        });
        jPanel1.add(dropFaculty);

        jLabel7.setText("Level");
        jPanel1.add(jLabel7);

        dropLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));
        jPanel1.add(dropLevel);

        jLabel8.setText("Department");
        jPanel1.add(jLabel8);

        dropDepart.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computing", "Engineering", "Business", "Humanities", "Sciences" }));
        dropDepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropDepartActionPerformed(evt);
            }
        });
        jPanel1.add(dropDepart);

        jLabel9.setText("Rank");
        jPanel1.add(jLabel9);
        jPanel1.add(txtRank);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 96, 896, 184);

        jLabel1.setText("Add Lecturer");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(440, 30, 62, 14);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave);
        btnSave.setBounds(280, 298, 90, 35);

        jButton2.setText("Back");
        getContentPane().add(jButton2);
        jButton2.setBounds(137, 298, 90, 35);

        jButton3.setText("Genarate Rank");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(402, 298, 133, 35);

        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(553, 298, 90, 35);

        jLabel10.setPreferredSize(new java.awt.Dimension(1000, 460));
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 920, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dropFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropFacultyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropFacultyActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

         try {
            PreparedStatement st=con.prepareStatement("INSERT INTO `lecturers details`(`Employeeid`, `Lecturername`, `Faculty`, `Department`, `Center`, `Building`, `Level`, `Rank`) VALUES (?,?,?,?,?,?,?,?)");
            st.setString(1,txtEmpID.getText());
            st.setString(2, txtLecName.getText());
            st.setString(3, dropFaculty.getSelectedItem().toString());
            st.setString(4, dropDepart.getSelectedItem().toString());
            st.setString(5, dropCenter.getSelectedItem().toString());
            st.setString(6, dropBuilding.getSelectedItem().toString());
            st.setString(7, dropLevel.getSelectedItem().toString());
            st.setString(8, txtRank.getText());
            
            int count=st.executeUpdate();
            if(count>0){
               JOptionPane.showMessageDialog(null, "lecture is inserted");
            }

             new ManageLecturers().setVisible(true);
             
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null,e.getMessage());
        }
        
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtLecNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLecNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLecNameActionPerformed

    private void dropDepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropDepartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropDepartActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

       txtRank.setText(dropLevel.getSelectedItem().toString()+"."+txtEmpID.getText());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtEmpIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmpIDKeyTyped
        
        char a=evt.getKeyChar();
        
        if(!Character.isDigit(a)){
            evt.consume();
        }
    }//GEN-LAST:event_txtEmpIDKeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         Clear();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddLecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddLecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddLecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddLecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddLecturer().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> dropBuilding;
    private javax.swing.JComboBox<String> dropCenter;
    private javax.swing.JComboBox<String> dropDepart;
    private javax.swing.JComboBox<String> dropFaculty;
    private javax.swing.JComboBox<String> dropLevel;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtEmpID;
    private javax.swing.JTextField txtLecName;
    private javax.swing.JTextField txtRank;
    // End of variables declaration//GEN-END:variables
}
