package timetablemanagement.View;

import timetablemanagement.Database.DBconnecter;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL'
 */
public class AddLocation extends javax.swing.JFrame {

    Connection con=null;
    /**
     * Creates new form AddLocation
     */
    public AddLocation() {
        initComponents();
        this.setResizable(false);
        con=DBconnecter.connection();
       
    }

     private void Clear(){
       
         txtLBuildingName.setText("");
         txtlRoomName.setText("");
         txtCapacity.setText("");
         btnLecHall.setSelected(false);
         btnLab.setSelected(false);
        
        // table_update();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnType = new javax.swing.ButtonGroup();
        txtLBuildingName = new javax.swing.JTextField();
        txtlRoomName = new javax.swing.JTextField();
        btnLab = new javax.swing.JRadioButton();
        btnLecHall = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCapacity = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(530, 390));
        getContentPane().setLayout(null);

        txtLBuildingName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtLBuildingName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLBuildingNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtLBuildingName);
        txtLBuildingName.setBounds(216, 100, 203, 30);

        txtlRoomName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txtlRoomName);
        txtlRoomName.setBounds(216, 138, 203, 30);

        btnType.add(btnLab);
        btnLab.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLab.setText("Laboratory");
        btnLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLabActionPerformed(evt);
            }
        });
        getContentPane().add(btnLab);
        btnLab.setBounds(333, 186, 120, 30);

        btnType.add(btnLecHall);
        btnLecHall.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLecHall.setText("Lecture Hall");
        btnLecHall.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLecHallMousePressed(evt);
            }
        });
        btnLecHall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLecHallActionPerformed(evt);
            }
        });
        getContentPane().add(btnLecHall);
        btnLecHall.setBounds(215, 186, 110, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Add Location");
        jLabel1.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(178, 11, 156, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Add room Building Wise:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(166, 58, 292, 36);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Building Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(88, 103, 110, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Room Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(88, 141, 85, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Room Type");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(91, 190, 79, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Capacity");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(91, 248, 59, 17);

        txtCapacity.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txtCapacity);
        txtCapacity.setBounds(216, 245, 203, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(371, 311, 73, 25);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Back");
        getContentPane().add(jButton2);
        jButton2.setBounds(102, 311, 73, 25);

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave);
        btnSave.setBounds(226, 311, 73, 25);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\add subject.jpg")); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(4, 4, 520, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLBuildingNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLBuildingNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLBuildingNameActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
       
        btnLab.setActionCommand("Laboratory");
        btnLecHall.setActionCommand("Lecture Hall");
        
         
         
            try {
                if(txtLBuildingName.getText().isEmpty()|| txtlRoomName.getText().isEmpty()||txtCapacity.getText().toString().isEmpty()){
                 JOptionPane.showMessageDialog(null, " please Enter the all colums");
                 throw new Exception(" please Enter the all colums");
            }
            PreparedStatement st=con.prepareStatement("INSERT INTO `locationdetails`(`buildingname`, `roomname`, `roomtype`, `capacity`) VALUES (?,?,?,?)");
           
            st.setString(1, txtLBuildingName.getText());
            st.setString(2, txtlRoomName.getText());
            st.setString(3, btnType.getSelection().getActionCommand());
            st.setString(4, txtCapacity.getText());
           
           
            int count=st.executeUpdate();
            if(count>0){
               JOptionPane.showMessageDialog(null, "location is inserted");
            }

            new Managelocation().setVisible(true);
             
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "error");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLabActionPerformed

    private void btnLecHallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLecHallActionPerformed
       
    }//GEN-LAST:event_btnLecHallActionPerformed

    private void btnLecHallMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLecHallMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLecHallMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Clear();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddLocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddLocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddLocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddLocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddLocation().setVisible(true);
                 
                 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnLab;
    private javax.swing.JRadioButton btnLecHall;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup btnType;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtCapacity;
    private javax.swing.JTextField txtLBuildingName;
    private javax.swing.JTextField txtlRoomName;
    // End of variables declaration//GEN-END:variables
}
