package timetablemanagement.View;

import timetablemanagement.Database.DBconnecter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL'
 */
public class Managelocation extends javax.swing.JFrame {

    Connection con=null;
    /**
     * Creates new form Managelocation
     */
    public Managelocation() {
        initComponents();
        this.setResizable(false);
        con=DBconnecter.connection();
         table_update();
        Clear();
    }

     private void Clear(){
       
         txtLBuildingName.setText("");
         txtlRoomName.setText("");
         txtCapacity.setText("");
         btnLecHall.setSelected(false);
         btnLab.setSelected(false);
        
         table_update();
    }
     
     
     private void table_update(){
        int c;
        try {
            PreparedStatement st=con.prepareStatement("SELECT `ID`, `buildingname`, `roomname`, `roomtype`, `capacity` FROM `locationdetails`");
            
            
            ResultSet rs=st.executeQuery();
            ResultSetMetaData rss=rs.getMetaData();
            c=rss.getColumnCount();
            
            DefaultTableModel df=(DefaultTableModel)ManageLOC.getModel();
            df.setRowCount(0);
            
            while(rs.next()){
                Vector v1=new Vector();
                
                for(int a=1;a<=c;a++){
                   
                    v1.add(rs.getString(1)); 
                    v1.add(rs.getString(3)); 
                    v1.add(rs.getString(2));  
                    v1.add(rs.getString(4));  
                    v1.add(rs.getString(5));  
                   
                }
                df.addRow(v1);

            }
            
          

             
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null,e.getMessage());
        }
        
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ManageLOC = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        txtLBuildingName = new javax.swing.JTextField();
        txtlRoomName = new javax.swing.JTextField();
        btnLecHall = new javax.swing.JRadioButton();
        btnLab = new javax.swing.JRadioButton();
        txtCapacity = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(740, 428));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Manage Location");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 30, 203, 29);

        ManageLOC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ManageLOC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "buildingname", "roomname", "roomtype", "capacity"
            }
        ));
        ManageLOC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageLOCMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ManageLOC);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(42, 89, 540, 105);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(640, 80, 83, 25);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(640, 120, 83, 25);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(640, 160, 83, 25);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Building Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(42, 231, 99, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Room Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(42, 285, 85, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Room Type");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(409, 228, 79, 23);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Capacity");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(409, 280, 94, 26);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Back");
        getContentPane().add(jButton4);
        jButton4.setBounds(52, 348, 104, 25);

        txtLBuildingName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLBuildingNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtLBuildingName);
        txtLBuildingName.setBounds(170, 230, 203, 30);

        txtlRoomName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlRoomNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtlRoomName);
        txtlRoomName.setBounds(170, 280, 203, 30);

        buttonGroup1.add(btnLecHall);
        btnLecHall.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLecHall.setText("Lecture Hall");
        btnLecHall.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLecHallMousePressed(evt);
            }
        });
        btnLecHall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLecHallActionPerformed(evt);
            }
        });
        getContentPane().add(btnLecHall);
        btnLecHall.setBounds(506, 228, 107, 25);

        buttonGroup1.add(btnLab);
        btnLab.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLab.setText("Laboratory");
        btnLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLabActionPerformed(evt);
            }
        });
        getContentPane().add(btnLab);
        btnLab.setBounds(617, 228, 103, 25);
        getContentPane().add(txtCapacity);
        txtCapacity.setBounds(510, 280, 203, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\add subject.jpg")); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 740, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        btnLecHall.setActionCommand("Lecture Hall");
        btnLab.setActionCommand("Laboratory");
        
        DefaultTableModel df=(DefaultTableModel)ManageLOC.getModel();
        int SelectedIndex=ManageLOC.getSelectedRow();
     
        String id=df.getValueAt(SelectedIndex,0).toString();
        try {
            PreparedStatement st=con.prepareStatement("UPDATE `locationdetails` SET `buildingname`=?,`roomname`=?,`roomtype`=?,`capacity`=? WHERE ID="+id+"");
             st.setString(1, txtLBuildingName.getText());
            st.setString(2, txtlRoomName.getText());
            st.setString(3,buttonGroup1.getSelection().getActionCommand());
            st.setString(4, txtCapacity.getText());
            if(txtLBuildingName.getText().isEmpty()|| txtlRoomName.getText().isEmpty()||txtCapacity.getText().toString().isEmpty()||buttonGroup1.getSelection().getActionCommand().isEmpty()){
                 JOptionPane.showMessageDialog(null, " please Enter the all colums");
                 throw new Exception();
            }
             int count=st.executeUpdate();
            if(count>0){
               JOptionPane.showMessageDialog(null, "Succesfully updated");
               table_update();
            
               Clear();
            }
                    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        DefaultTableModel df=(DefaultTableModel)ManageLOC.getModel();
        int SelectedIndex=ManageLOC.getSelectedRow();
     
        String id=df.getValueAt(SelectedIndex,0).toString();
        
        try {
            PreparedStatement st1=con.prepareStatement("DELETE FROM `locationdetails`  WHERE ID="+id+"");
             int count=st1.executeUpdate();
            if(count>0){
               JOptionPane.showMessageDialog(null, "Succesfully deleted");
               table_update();
               Clear();
            }
                    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtLBuildingNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLBuildingNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLBuildingNameActionPerformed

    private void btnLecHallMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLecHallMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLecHallMousePressed

    private void btnLecHallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLecHallActionPerformed

    }//GEN-LAST:event_btnLecHallActionPerformed

    private void btnLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLabActionPerformed

    private void txtlRoomNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlRoomNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlRoomNameActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Clear();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ManageLOCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageLOCMouseClicked
        
        
         
        DefaultTableModel df=(DefaultTableModel)ManageLOC.getModel();
     int SelectedIndex=ManageLOC.getSelectedRow();
     
     String ID=df.getValueAt(SelectedIndex,0).toString();
     
     try {
            PreparedStatement st1=con.prepareStatement("SELECT `buildingname`, `roomname`, `roomtype`, `capacity` FROM `locationdetails`  WHERE ID="+ID+"");
            
            
            ResultSet rs1=st1.executeQuery();
            while(rs1.next()){
                txtLBuildingName.setText(rs1.getString(1));
                txtlRoomName.setText(rs1.getString(2));
                String type=rs1.getString(3);
                if(type.equals("Lecture Hall")){
                    btnLecHall.setSelected(true);
                }else{
                    btnLab.setSelected(true);
                }
                
               
                txtCapacity.setText(rs1.getString(4));
            
              
                
            }
            
          

             
        } catch (Exception e) {
             e.printStackTrace();
             
        }
    }//GEN-LAST:event_ManageLOCMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Managelocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Managelocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Managelocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Managelocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Managelocation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ManageLOC;
    private javax.swing.JRadioButton btnLab;
    private javax.swing.JRadioButton btnLecHall;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCapacity;
    private javax.swing.JTextField txtLBuildingName;
    private javax.swing.JTextField txtlRoomName;
    // End of variables declaration//GEN-END:variables
}
