package timetablemanagement.View;

import timetablemanagement.Database.DBconnecter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL'
 */
public class ManageSessionRooms extends javax.swing.JFrame {
      Connection con=null;
      int[] id=new int[20];
      int[] rid=new int[20];
    
    /**
     * Creates new form ManageSessionRooms
     */
    public ManageSessionRooms() {
        initComponents();
        this.setResizable(false);
        con=DBconnecter.connection();
        detail.setEditable(false);
        getsessionDetail();
        getroomDetail();
    }
    
     private void Clear(){
        
          room.setSelectedIndex(0);
          session.setSelectedIndex(0);
          detail.setText("");
        
    }
    
    private void getsessionDetail(){
        int i=0;
        try {
           
            PreparedStatement st=con.prepareStatement("SELECT * FROM `sessiondetails`");
           
            ResultSet rs=st.executeQuery();
            session.addItem(null);
            while(rs.next()){
                  id[i]=rs.getInt(1);
                  session.addItem(rs.getString(1)+"--"+rs.getString(2)+"--"+rs.getString(4)+"--"+rs.getString(5)+"--"+rs.getString(6)); 
                  i++;
            }
          
          
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }
    private void getroomDetail(){
        int i=0;
        try {
            
            PreparedStatement st1=con.prepareStatement("SELECT * FROM `locationdetails`");
           
            ResultSet rs1=st1.executeQuery();
            room.addItem(null);
            while(rs1.next()){
                  rid[i]=rs1.getInt(1);
                  room.addItem(rs1.getString(3)); 
                   i++;
            }
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        session = new javax.swing.JComboBox<>();
        room = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        detail = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 390));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Manage Session Rooms");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(105, 11, 279, 29);

        session.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sessionActionPerformed(evt);
            }
        });
        getContentPane().add(session);
        session.setBounds(194, 94, 262, 22);

        room.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomActionPerformed(evt);
            }
        });
        getContentPane().add(room);
        room.setBounds(194, 134, 262, 22);

        jLabel2.setText("Select Session");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(52, 98, 100, 14);

        jLabel3.setText("Select Room");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(53, 138, 90, 14);

        jLabel4.setText("Selected Session");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(54, 174, 110, 14);

        jButton1.setText("Back");
        getContentPane().add(jButton1);
        jButton1.setBounds(115, 313, 73, 23);

        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(241, 313, 73, 23);

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(367, 313, 73, 23);

        detail.setColumns(20);
        detail.setRows(5);
        jScrollPane1.setViewportView(detail);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(194, 174, 262, 121);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\add subject.jpg")); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 500, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void roomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomActionPerformed

    private void sessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sessionActionPerformed
      
       
        try {
             if(session.getSelectedItem()!=null){
            String value=session.getSelectedItem().toString();
            
            value=value.replaceAll("--", "\n");
                   detail.setText(value);

           }
            
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null,e.getMessage());
        }
       
        
        
    }//GEN-LAST:event_sessionActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
             
              try {
               if(session.getSelectedIndex()>0 && room.getSelectedIndex()>0){
            PreparedStatement st=con.prepareStatement("INSERT INTO `sessionrooms`(`ID`, `session`, `room`) VALUES (?,?,?)");
           
            st.setInt(1,0 );
            st.setInt(2,id[session.getSelectedIndex()-1]);
            st.setInt(3,rid[room.getSelectedIndex()-1]);
           
           
            int count=st.executeUpdate();
            if(count>0){
               JOptionPane.showMessageDialog(null, "Room added");
               new AddLocations().setVisible(true);
            }
               }else{
                   JOptionPane.showMessageDialog(null, "please insert details");
               }
             
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "error");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Clear();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageSessionRooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageSessionRooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageSessionRooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageSessionRooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageSessionRooms().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea detail;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> room;
    private javax.swing.JComboBox<String> session;
    // End of variables declaration//GEN-END:variables
}
